CREATE_USER_TABLE = """
CREATE TABLE IF NOT EXISTS telegram_users(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USER_NAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE(TELEGRAM_ID)
)
"""


INSERT_USER_TABLE = """
INSERT INTO telegram_users VALUES (?, ?, ?, ?, ?)
"""

READ_USER_TABLE = """
SELECT ID, USER_NAME, FIRST_NAME, LAST_NAME FROM telegram_users
"""
