CREATE_USER_TABLE = """
CREATE TABLE IF NOT EXISTS telegram_users(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USER_NAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE(TELEGRAM_ID)
)
"""

ALTER_USER_TABLE_V1 = """
ALTER TABLE telegram_users ADD COLUMN REVERENCE_LINK TEXT
"""

ALTER_USER_TABLE_V2 = """
ALTER TABLE telegram_users ADD COLUMN BALANCE INTEGER
"""


INSERT_USER_TABLE = """
INSERT INTO telegram_users VALUES (?, ?, ?, ?, ?, ?, ?)
"""

READ_USER_TABLE = """
SELECT ID, USER_NAME, FIRST_NAME, LAST_NAME FROM telegram_users
"""

READ_ALL_USER_TABLE = """
SELECT * FROM telegram_users WHERE TELEGRAM_ID = ?
"""

READ_USER_TABLE_BY_LINK = """
SELECT * FROM telegram_users WHERE REVERENCE_LINK = ?
"""



CREATE_PROFILE_TABLE = """
CREATE TABLE IF NOT EXISTS profiles(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
PHONE_NUMBER INTEGER,
EMAIL CHAR(50),
BIO CHAR(50),
PHOTO TEXT,

UNIQUE(TELEGRAM_ID)
)
"""

INSERT_PROFILE_TABLE = """
INSERT INTO profiles VALUES (?, ?, ?, ?, ?, ?, ?)
"""

READ_PROFLE_TABLE = """
SELECT * FROM profiles WHERE TELEGRAM_ID=?
"""

UPDATE_PROFILE_TABLE = """
UPDATE profiles SET NICKNAME = ?, PHONE_NUMBER = ?, EMAIL = ?, BIO = ?, PHOTO = ? WHERE TELEGRAM_ID = ?
"""

DELETE_PROFILE = """
DELETE FROM profiles WHERE TELEGRAM_ID=?
"""

READ_ALL_PROFILES = """
SELECT * FROM profiles p 
WHERE p.TELEGRAM_ID NOT IN (
        SELECT ld.OWNER_TELEGRAM_ID 
        FROM like_dislike ld WHERE LIKER_TELEGRAM_ID=? 
        AND ld.LIKE_DISLIKE_STATUS IS NOT NULL
)
AND p.TELEGRAM_ID!=?
"""

CREATE_LIKE_DISLIKE_TABLE = """
CREATE TABLE IF NOT EXISTS like_dislike(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
LIKER_TELEGRAM_ID INTEGER,
LIKE_DISLIKE_STATUS INTEGER,

UNIQUE(OWNER_TELEGRAM_ID, LIKER_TELEGRAM_ID)
)
"""

INSERT_LIKE_TABLE = """
INSERT INTO like_dislike VALUES (?, ?, ?, ?)
"""

INSERT_DISLIKE_TABLE = """
INSERT INTO like_dislike VALUES (?, ?, ?, ?)
"""

CREATE_REVERENCE_TABLE = """
CREATE TABLE IF NOT EXISTS reverence(
ID INTEGER PRIMARY KEY,
OWNER_TELEGRAM_ID INTEGER,
REVERENCE_TELEGRAM_ID INTEGER,
UNIQUE(OWNER_TELEGRAM_ID, REVERENCE_TELEGRAM_ID)
)
"""

INSERT_REVERENCE_USER = """
INSERT INTO reverence VALUES (?, ?, ?)
"""

UPDATE_REVERENCE_USER_LINK = """
UPDATE telegram_users SET REVERENCE_LINK = ? WHERE TELEGRAM_ID = ?
"""

UPDATE_REVERENCE_USER_BALANCE = """
UPDATE telegram_users SET BALANCE = COALESCE(BALANCE, 0) + 100 WHERE TELEGRAM_ID = ?
"""


READ_REVERENCE_USER = """
SELECT * FROM reverence WHERE OWNER_TELEGRAM_ID = ?
"""